### ISSUE TITLE
Message reception does not work

### ISSUE THREAD

**Issue by Bettman66** [tomek-o/tSIP-plugin-TcpServer#1]
I tested the plugin and sending commands works great, but I don't receive any messages unless I request them with the "local util = require("scripts.server_util"); util.report_call_state("INITIAL_CALL_REPORT")" command.

**Comment by tomek-o** [comment]
Have you assigned server_util.lua to "on call state" event (Settings/Scripts)? Alternatively, if another script is already assigned there then similar construction like one for initial notification can be added to already used script:

`local util = require("scripts.server_util"); util.report_call_state("OPTIONAL_TAG")`

**Comment by Bettman66** [comment]
Great, that's it, thanks.
